---
fields:
  - 'dataset_region'
  - 'seedlen'
  - 'pathno'
  - 'patched'
  - 'context'
  - 'readsindex'
  - 'chunksize'
  - 'stepsize'
  - 'pathpicktime'
  - 'pathindextime'
  - 'pathsavetime'
  - 'pindexsize'
  - 'locino'
  - 'uniqnodes'
  - 'totalnodes'
  - 'pathquerytimeperchunk'
  - 'traversetimeperchunk'
  - 'nofdonechunks'
  - 'totalhits'
  - 'seedsonpaths'
  - 'coveredreads'
  - 'nofgodowns'
#  - 'traversetime'
#  - 'pathquerytime'
  - 'seedfindingtime'
reduce:
  dataset_region:
    - 'parse'
    - '.*/([^/]+)(/[^/]+).xg'
  pathquerytimeperchunk: 'avg_tp'
  seedsonpaths: 'sum'
  traversetimeperchunk: 'avg_tp'
  nofdonechunks: 'count'
  pindexsize: 'filesize_glob'
patterns:
  - 'Seed length:{:s}{seedlen:d}'
  - 'Number of paths:{:s}{pathno:d}'
  - 'Context length (used in patching):{:s}{context:d}'
  - 'Patched:{:s}{patched:w}'
  - "Paths index file:{:s}'{pindexsize}'"
  - 'Reads chunk size:{:s}{chunksize:d}'
  - 'Reads index type:{:s}{readsindex:w}'
  - 'Step size:{:s}{stepsize:d}'
  - "Loading the graph from file '{dataset_region}'..."
  - 'Picked paths in {pathpicktime:d} us.'
  - 'Indexed paths in {pathindextime:d} us.'
  - 'Saved path index in {pathsavetime:d} us.'
  - 'Number of starting loci selected (in {uniqnodes:d} nodes of total {totalnodes:d}): {locino:d}'
  - 'Found seed on paths in {pathquerytimeperchunk:d} us.'
  - 'Total number of seeds found on paths:{:s}{seedsonpaths:d}'
  - 'Traversed in {traversetimeperchunk:d} us.'
  - 'Traversed in {nofdonechunks:d} us.'
  - 'Total number of seeds found:{:s}{totalhits:d}'
  - 'Total number of reads covered:{:s}{coveredreads:d}'
  - "Total number of 'godown' operations:{:s}{nofgodowns:d}"
#  - 'traverse:{:s}{traversetime:d} us'
#  - 'paths-seed-find:{:s}{pathquerytime:d} us'
  - 'seed-finding:{:s}{seedfindingtime:d} us'
...
